LP-2377 Add experience view and apis
OmnipreneurshipAcademy/edx-platform pull request #132
Opened 2021-01-18 11:49 UTC by zeshanarifios

[LP-2377](https://philanthropyu.atlassian.net/browse/LP-2377)

2021-01-18 12:58 UTC, annas-usman requested changes
Left some comments

2021-01-18 13:02 UTC, annas-usman requested changes

2021-01-19 15:53 UTC, ahmed-faraz46 requested changes

2021-01-19 15:53 UTC, ahmed-faraz46 commented on openedx/adg/lms/applications/migrations/0006_auto_20210116_1528.py
> +        ),
Let's please remove these operation, if possible take latest pull from master, as we have fixed this issue in [LP-2498 ](https://philanthropyu.atlassian.net/browse/LP-2498)

2021-01-19 15:53 UTC, ahmed-faraz46 commented on openedx/adg/lms/applications/api_views.py
> +                WorkExperience.objects.filter(user_application=user_application).delete()
We can change it to `user.application.applications_workexperiences.all().delete()` more django specific.

2021-02-01 21:42 UTC, zeshanarifios commented
https://github.com/OmnipreneurshipAcademy/edx-platform/pull/143

2021-02-01 21:42 UTC, closed without merging