LP-2576 Make mandrill client asynchronous
OmnipreneurshipAcademy/edx-platform pull request #188
Opened 2021-03-04 11:52 UTC by annas-usman

[Ticket](https://philanthropyu.atlassian.net/browse/LP-2576)

2021-03-04 11:58 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1212/workflows/workflows_id/jobs/1212/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/tasks.py (100%)
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   43 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2021-03-04 13:56 UTC, asadali145 approved these changes
LGTM

2021-03-04 14:17 UTC, emraan004 requested changes

2021-03-04 14:17 UTC, emraan004 commented on openedx/adg/lms/applications/admin.py
> +        task_send_mandrill_email.delay(
I think this function will break when it will run celery environment, you need to pass serializable object to celery task

2021-03-04 14:17 UTC, emraan004 commented on openedx/adg/lms/applications/helpers.py
> +    task_send_mandrill_email.delay(MandrillClient.APPLICATION_SUBMISSION_CONFIRMATION, recipient_email, context)
Same here, you need to pass serializable object to celery task

2021-03-04 14:17 UTC, emraan004 commented on openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py
> +    mock_send_mandrill_email.delay.assert_called_once_with(
you need to pass serializable object to celery task

2021-03-04 14:17 UTC, emraan004 commented on openedx/adg/lms/student/helpers.py
> +    task_send_mandrill_email.delay(MandrillClient.USER_ACCOUNT_ACTIVATION, user.email, context)
Please verify it, I could be wrong but you need to pass serializable object to celery task everywhere

2021-03-04 15:39 UTC, emraan004 approved these changes
LGTM 👍

2021-03-04 18:05 UTC, ahmed-faraz46 requested changes
Just one minor suggestion, rest looks perfect 👍

2021-03-05 07:28 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1221/workflows/workflows_id/jobs/1221/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/tasks.py (100%)
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   43 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2021-03-05 07:56 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1222/workflows/workflows_id/jobs/1222/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/tasks.py (100%)
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   44 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2021-03-05 10:45 UTC, ahmed-faraz46 approved these changes
Looks good 👍 But please add some logs in `task_send_mandrill_email` and `send_mandrill_email` method.

2021-03-05 13:10 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1229/workflows/workflows_id/jobs/1229/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (0.0%): Missing lines 67
openedx/adg/common/lib/mandrill_client/tasks.py (100%)
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   48 lines
Missing: 1 line
Coverage: 97%
-------------
```

2021-03-05 14:17 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1233/workflows/workflows_id/jobs/1233/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (0.0%): Missing lines 67
openedx/adg/common/lib/mandrill_client/tasks.py (100%)
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   48 lines
Missing: 1 line
Coverage: 97%
-------------
```

2021-03-08 06:53 UTC, merged