Zahid/lp 2431
OmnipreneurshipAcademy/edx-platform pull request #19
Opened 2020-10-28 15:29 UTC by zahid-arbisoft

2020-11-01 13:10 UTC, zahid-arbisoft commented
Test

2020-11-01 14:27 UTC, zahid-arbisoft commented
$report

2020-11-01 14:37 UTC, zahid-arbisoft commented
abc

2020-11-01 14:46 UTC, zahid-arbisoft commented
test

2020-11-01 14:47 UTC, zahid-arbisoft commented
$body

2020-11-01 15:58 UTC, zahid-arbisoft commented
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------

2020-11-01 17:24 UTC, zahid-arbisoft commented
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------

2020-11-01 17:25 UTC, zahid-arbisoft commented
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
------------- 
Check-out [tests](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/289/workflows/08b30f6a-6b9d-4eb0-8fe7-922c5b759e3d/jobs/297/tests) and coverage [reports](artifacts)
```

2020-11-01 17:56 UTC, zahid-arbisoft commented
```
## Diff Coverage Report
Check-out complete **[report](artifacts)** and other artifacts.

-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-01 17:58 UTC, zahid-arbisoft commented
## Diff Coverage Report
Check-out complete **[report](artifacts)** and other artifacts.
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-01 18:35 UTC, zahid-arbisoft commented
This test message

2020-11-01 18:36 UTC, zahid-arbisoft commented
This test message

2020-11-01 18:52 UTC, zahid-arbisoft commented
This test message

2020-11-01 19:42 UTC, zahid-arbisoft commented
## Diff Coverage Report
Check-out complete **[report](link)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-01 22:12 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/318/workflows/workflows_id/jobs/318/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-01 22:26 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/319/workflows/workflows_id/jobs/319/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-01 22:30 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/320/workflows/workflows_id/jobs/320/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-02 07:18 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/324/workflows/workflows_id/jobs/324/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-02 14:17 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/334/workflows/workflows_id/jobs/334/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-02 14:37 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/336/workflows/workflows_id/jobs/336/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-02 17:58 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/340/workflows/workflows_id/jobs/340/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
conftest.py (100%)
-------------
Total:   8 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2020-11-02 23:24 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/342/workflows/workflows_id/jobs/342/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
cms/djangoapps/pipeline_js/test_my_functinon_ok.py (100%)
cms/djangoapps/pipeline_js/utils.py (100%)
conftest.py (100%)
lms/djangoapps/commerce/utils.py (20.0%): Missing lines 421-424
lms/djangoapps/survey/tests/test_utils.py (100%)
lms/djangoapps/survey/tests/test_views.py (100%)
lms/djangoapps/survey/utils.py (100%)
openedx/adg/lms/applications/utils.py (0.0%): Missing lines 1-2,4-6,9,20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71,74-77
pavelib/utils/envs.py (0.0%): Missing lines 224
pavelib/utils/test/suites/pytest_suite.py (0.0%): Missing lines 252-255,257
scripts/xsslint/tests/test_utils.py (100%)
scripts/xsslint/xsslint/utils.py (100%)
-------------
Total:   91 lines
Missing: 61 lines
Coverage: 32%
-------------
```

2020-11-03 08:14 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/344/workflows/workflows_id/jobs/344/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
cms/djangoapps/pipeline_js/test_my_functinon_ok.py (100%)
cms/djangoapps/pipeline_js/utils.py (100%)
conftest.py (100%)
lms/djangoapps/commerce/utils.py (20.0%): Missing lines 421-424
lms/djangoapps/survey/tests/test_utils.py (100%)
lms/djangoapps/survey/utils.py (100%)
openedx/adg/lms/applications/utils.py (0.0%): Missing lines 1-2,4-6,9,20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71,74-77
scripts/xsslint/tests/test_utils.py (100%)
scripts/xsslint/xsslint/utils.py (100%)
-------------
Total:   86 lines
Missing: 55 lines
Coverage: 36%
-------------
```

2020-11-03 09:30 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/345/workflows/workflows_id/jobs/345/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-03 09:32 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/346/workflows/workflows_id/jobs/346/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
cms/djangoapps/pipeline_js/test_my_functinon_ok.py (100%)
cms/djangoapps/pipeline_js/utils.py (100%)
conftest.py (100%)
lms/djangoapps/commerce/utils.py (20.0%): Missing lines 421-424
lms/djangoapps/survey/tests/test_utils.py (100%)
lms/djangoapps/survey/utils.py (100%)
openedx/adg/lms/applications/utils.py (0.0%): Missing lines 1-2,4-6,9,20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71,74-77
pavelib/utils/envs.py (0.0%): Missing lines 224
pavelib/utils/test/suites/pytest_suite.py (0.0%): Missing lines 252-255,257
scripts/xsslint/tests/test_utils.py (100%)
scripts/xsslint/xsslint/utils.py (100%)
-------------
Total:   92 lines
Missing: 61 lines
Coverage: 33%
-------------
```

2020-11-03 09:42 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/349/workflows/workflows_id/jobs/349/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-03 09:45 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/350/workflows/workflows_id/jobs/350/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
cms/djangoapps/pipeline_js/test_my_functinon_ok.py (100%)
cms/djangoapps/pipeline_js/utils.py (100%)
conftest.py (100%)
lms/djangoapps/commerce/utils.py (20.0%): Missing lines 421-424
lms/djangoapps/survey/tests/test_utils.py (100%)
lms/djangoapps/survey/utils.py (100%)
openedx/adg/lms/applications/utils.py (0.0%): Missing lines 1-2,4-6,9,20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71,74-77
pavelib/utils/envs.py (0.0%): Missing lines 224
pavelib/utils/test/suites/pytest_suite.py (0.0%): Missing lines 252-255,257
scripts/xsslint/tests/test_utils.py (100%)
scripts/xsslint/xsslint/utils.py (100%)
-------------
Total:   92 lines
Missing: 61 lines
Coverage: 33%
-------------
```

2020-11-03 10:16 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG ((Failed))
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/353/workflows/workflows_id/jobs/353/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-03 10:57 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/354/workflows/workflows_id/jobs/354/artifacts)**. Coverage !!! Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-03 11:26 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/358/workflows/workflows_id/jobs/358/artifacts)**. Coverage !!! Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   56 lines
Missing: 41 lines
Coverage: 26%
-------------
```

2020-11-03 12:36 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx ((Failed))
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/352/workflows/workflows_id/jobs/352/artifacts)**.
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
cms/djangoapps/pipeline_js/test_my_functinon_ok.py (100%)
cms/djangoapps/pipeline_js/utils.py (100%)
conftest.py (100%)
lms/djangoapps/commerce/utils.py (20.0%): Missing lines 421-424
lms/djangoapps/survey/tests/test_utils.py (100%)
lms/djangoapps/survey/utils.py (100%)
openedx/adg/lms/applications/utils.py (0.0%): Missing lines 1-2,4-6,9,20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71,74-77
scripts/xsslint/tests/test_utils.py (100%)
scripts/xsslint/xsslint/utils.py (100%)
-------------
Total:   86 lines
Missing: 55 lines
Coverage: 36%
-------------
```

2020-11-03 13:39 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/359/workflows/workflows_id/jobs/359/artifacts)**. Coverage !!! Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
cms/djangoapps/pipeline_js/test_my_functinon_ok.py (100%)
cms/djangoapps/pipeline_js/utils.py (100%)
conftest.py (100%)
lms/djangoapps/commerce/utils.py (20.0%): Missing lines 421-424
lms/djangoapps/survey/tests/test_utils.py (100%)
lms/djangoapps/survey/utils.py (100%)
openedx/adg/lms/applications/utils.py (0.0%): Missing lines 1-2,4-6,9,20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71,74-77
scripts/xsslint/tests/test_utils.py (100%)
scripts/xsslint/xsslint/utils.py (100%)
-------------
Total:   86 lines
Missing: 55 lines
Coverage: 36%
-------------
```

2020-11-03 17:34 UTC, zahid-arbisoft commented
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/368/workflows/workflows_id/jobs/368/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
cms/djangoapps/pipeline_js/test_my_functinon_ok.py (100%)
cms/djangoapps/pipeline_js/utils.py (55.6%): Missing lines 14-17
conftest.py (100%)
lms/djangoapps/commerce/utils.py (20.0%): Missing lines 421-424
lms/djangoapps/survey/tests/test_utils.py (100%)
lms/djangoapps/survey/utils.py (100%)
openedx/adg/cms/test_sss.py (100%)
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
pavelib/utils/envs.py (0.0%): Missing lines 224
pavelib/utils/test/suites/pytest_suite.py (0.0%): Missing lines 252-255,257
scripts/xsslint/tests/test_utils.py (100%)
scripts/xsslint/xsslint/utils.py (100%)
-------------
Total:   105 lines
Missing: 55 lines
Coverage: 47%
-------------
```

2020-11-03 17:52 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/369/workflows/workflows_id/jobs/369/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/cms/test_sss.py (100%)
openedx/adg/lms/applications/tests/test_utils.py (100%)
openedx/adg/lms/applications/utils.py (19.6%): Missing lines 20-26,28,30-36,38,40-46,48,50-56,58,61-67,69,71
-------------
Total:   59 lines
Missing: 41 lines
Coverage: 30%
-------------
```

2020-11-03 18:15 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/370/workflows/workflows_id/jobs/370/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

2020-11-03 18:22 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/371/workflows/workflows_id/jobs/371/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

2020-11-03 18:38 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/372/workflows/workflows_id/jobs/372/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

2020-11-03 18:52 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/373/workflows/workflows_id/jobs/373/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

2020-11-03 20:10 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/378/workflows/workflows_id/jobs/378/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

2020-11-03 20:11 UTC, zahid-arbisoft commented
> **pylint:** ❌
> **pycodestyle:** ✔️
> **iSort:** ❌
> 
> **Please fix following pylint issues:**
> 
> ```
> ************* Module edx-platform.conftest
> conftest.py:23:0: C0116: Missing function or method docstring (missing-function-docstring)
> 
> -----------------------------------
> Your code has been rated at 9.80/10
> ```
> 
> **Please fix following iSort issues:**
> 
> ```
>  ERROR: /conftest.py Imports are incorrectly sorted. 
> ```

These are core changes

2020-11-04 08:11 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/382/workflows/workflows_id/jobs/382/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/utils/tests/tests_date_utils.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2020-11-04 08:17 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/383/workflows/workflows_id/jobs/383/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/utils/tests/tests_date_utils.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2020-11-10 07:25 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/388/workflows/workflows_id/jobs/388/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/utils/tests/tests_date_utils.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2020-11-10 08:37 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/389/workflows/workflows_id/jobs/389/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/utils/tests/tests_date_utils.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2020-11-10 09:29 UTC, zeshanarifios requested changes

2020-11-10 09:29 UTC, zeshanarifios commented on adg/pipelines/scripts/post_comment.py
> +parser.add_argument('--type', '-t', help='Report type i.e. AAG, Edx')
Please fix typo 
AAG -> ADG

2020-11-10 09:45 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/390/workflows/workflows_id/jobs/390/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/utils/tests/tests_date_utils.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2020-11-10 09:46 UTC, zeshanarifios approved these changes
👍 LGTM

2020-11-10 10:52 UTC, harris-irfan commented on adg/pipelines/scripts/post_comment.py
> +    url = "https://api.github.com/repos/{username}/{repo}/issues/{pr}/comments".format(
single qoutes

2020-11-10 10:58 UTC, harris-irfan approved these changes
Just a couple of comments related to single qoutes usage.

2020-11-10 10:58 UTC, harris-irfan commented on adg/pipelines/scripts/post_comment.py
> +    print("Comment status: ", response.status_code, response.reason)
single qoutes

2020-11-10 10:58 UTC, harris-irfan commented on adg/pipelines/scripts/post_comment.py
> +    url = "https://api.github.com/repos/{username}/{repo}/issues/{pr}/comments".format(
single qoutes

2020-11-10 11:11 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/393/workflows/workflows_id/jobs/393/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/utils/tests/tests_date_utils.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2020-11-10 11:12 UTC, merged