LP-2630 - Add mandrill support for multiple emails
OmnipreneurshipAcademy/edx-platform pull request #245
Opened 2021-04-06 15:46 UTC by MunamMubashir-arbisoft

[LP-2630](https://philanthropyu.atlassian.net/browse/LP-2630)

- Add mandrill support for a group of email addresses to send the email to.
- Change all the occurrences of the send email task to conform with the new changes.

2021-04-06 15:49 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1440/workflows/workflows_id/jobs/1440/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (33.3%): Missing lines 71-72
openedx/adg/common/lib/mandrill_client/email_data.py (100%)
openedx/adg/common/lib/mandrill_client/tasks.py (90.9%): Missing lines 34
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
-------------
Total:   25 lines
Missing: 3 lines
Coverage: 88%
-------------
```

2021-04-06 16:30 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1442/workflows/workflows_id/jobs/1442/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (33.3%): Missing lines 71-72
openedx/adg/common/lib/mandrill_client/email_data.py (100%)
openedx/adg/common/lib/mandrill_client/tasks.py (100%)
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
-------------
Total:   24 lines
Missing: 2 lines
Coverage: 91%
-------------
```

2021-04-06 18:02 UTC, zahid-arbisoft requested changes

2021-04-06 18:13 UTC, MunamMubashir-arbisoft commented on openedx/adg/common/lib/mandrill_client/tests/test_tasks.py
>      mock_mandrill_client.assert_called_once()
Actually this was a single point ticket that blocked a few others so we wanted to get this done sooner, therefore I didn't really go through the unit tests properly.
However, this is a good suggestion. And I'll cater it soon

2021-04-06 18:16 UTC, zahid-arbisoft commented on openedx/adg/common/lib/mandrill_client/tests/test_tasks.py
>      mock_mandrill_client.assert_called_once()
In that case, I can approve PR, you can create a follow-up PR or separate story for the unit test. WDYT

2021-04-06 18:17 UTC, MunamMubashir-arbisoft commented on openedx/adg/common/lib/mandrill_client/tests/test_tasks.py
>      mock_mandrill_client.assert_called_once()
I'll add the test, no worries.

2021-04-06 18:28 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1443/workflows/workflows_id/jobs/1443/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (33.3%): Missing lines 71-72
openedx/adg/common/lib/mandrill_client/email_data.py (100%)
openedx/adg/common/lib/mandrill_client/tasks.py (100%)
openedx/adg/common/lib/mandrill_client/tests/test_tasks.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/student/helpers.py (100%)
-------------
Total:   26 lines
Missing: 2 lines
Coverage: 92%
-------------
```

2021-04-06 19:03 UTC, zahid-arbisoft approved these changes
LGTM, nice work 🚀

2021-04-07 05:28 UTC, asadali145 approved these changes

2021-04-07 08:07 UTC, merged