LP-2676 Write technical documentation for webinars app
OmnipreneurshipAcademy/edx-platform pull request #294
Opened 2021-04-29 17:56 UTC by harris-irfan

Ticket: [LP-2676](https://philanthropyu.atlassian.net/browse/LP-2676)

2021-04-29 18:01 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1665/workflows/workflows_id/jobs/1665/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

2021-04-29 21:28 UTC, javeriaejaz-arbisoft approved these changes

2021-04-30 06:56 UTC, ahmed-faraz46 approved these changes
Just one suggestion, rest looks good 👍

2021-04-30 06:56 UTC, ahmed-faraz46 commented on openedx/adg/lms/webinars/__init__.py
> + - add event details like title, schedule, description, banner image, external meeting link for webinar
Let's not dive to such details that some small change in code would require a change in documentation. I guess Admins can add, update, cancel, clone existing events (The above paragraph) is enough for the purpose of technical documentation

2021-04-30 06:57 UTC, ahmed-faraz46 requested changes

2021-04-30 06:57 UTC, ahmed-faraz46 commented on openedx/adg/lms/webinars/__init__.py
> + - add event details like title, schedule, description, banner image, external meeting link for webinar
.

2021-04-30 07:56 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1667/workflows/workflows_id/jobs/1667/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

2021-04-30 08:04 UTC, ahmed-faraz46 approved these changes

2021-04-30 11:06 UTC, asadali145 approved these changes

2021-04-30 11:07 UTC, merged