LP-2692 - Build a mechanism to support Business Line prerequisite courses
OmnipreneurshipAcademy/edx-platform pull request #336
Opened 2021-05-19 09:40 UTC by MunamMubashir-arbisoft

[LP-2692](https://philanthropyu.atlassian.net/browse/LP-2692)

- Update MultilingualCourseGroup model to allow common, program and specific Business Line prereqs
- Add Admin for MultilingualCourseGroup
- Add MultilingualCourseGroupForm to allow prereq related validations

2021-05-19 09:44 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1879/workflows/workflows_id/jobs/1879/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/admin.py (50.0%): Missing lines 229-234
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/factories.py (100%)
openedx/adg/lms/applications/tests/test_forms.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
-------------
Total:   53 lines
Missing: 6 lines
Coverage: 88%
-------------
```

2021-05-19 17:04 UTC, ahmed-faraz46 requested changes
Good work Munam 👏 Here are a few suggestions please look into them.

2021-05-19 17:04 UTC, ahmed-faraz46 commented on openedx/adg/lms/applications/models.py
> +        return self.business_line_prerequisite is not None
How about `bool(self.business_line_prerequisite)`?

2021-05-19 17:04 UTC, ahmed-faraz46 commented on openedx/adg/lms/applications/tests/test_forms.py
> +    assert form.is_valid() is expected_result
We should also verify if the error message is associated with correct field?

2021-05-20 07:25 UTC, annas-usman reviewed
Apart from the already requested changes everything looks good, just found a spelling mistake.

2021-05-20 07:25 UTC, annas-usman commented on openedx/adg/lms/applications/admin.py
> +            MultilingualCourseGroupForm: `MultilingualCourseGroupForm` with updated permissions rearding related
regarding*

2021-05-20 08:11 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/applications/constants.py
> +    'A Course Group can either be a prerequisite for the Program, specific Business Line or common for all'
The error message seems a bit ambiguous. Can we please change it along the line `A course group can only be a prerequisite for one of the following: ......` ?

2021-05-20 08:20 UTC, javeriaejaz-arbisoft reviewed
Just added a comment for error message. The rest looks fine, though we can improve the coverage by writing the test case for admin.

2021-05-20 09:04 UTC, MunamMubashir-arbisoft commented on openedx/adg/lms/applications/constants.py
> +    'A Course Group can either be a prerequisite for the Program, specific Business Line or common for all'
@javeriaejaz-arbisoft I have already added a similar message for the fieldset description.

2021-05-20 10:44 UTC, MunamMubashir-arbisoft commented
@ahmed-faraz46 I've added a custom migration. On my local deploy, all the data is being preserved with this. Please take a look.

2021-05-20 10:45 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1888/workflows/workflows_id/jobs/1888/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/admin.py (93.3%): Missing lines 216
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/conftest.py (100%)
openedx/adg/lms/applications/tests/factories.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_multilingual_course_group_admin.py (100%)
openedx/adg/lms/applications/tests/test_forms.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
-------------
Total:   75 lines
Missing: 1 line
Coverage: 98%
-------------
```

2021-05-20 10:58 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1889/workflows/workflows_id/jobs/1889/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/admin.py (93.3%): Missing lines 216
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/conftest.py (100%)
openedx/adg/lms/applications/tests/factories.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_multilingual_course_group_admin.py (100%)
openedx/adg/lms/applications/tests/test_forms.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
-------------
Total:   75 lines
Missing: 1 line
Coverage: 98%
-------------
```

2021-05-20 11:52 UTC, annas-usman approved these changes

2021-05-20 12:17 UTC, merged