LP-2712 Display business line courses in course catalog
OmnipreneurshipAcademy/edx-platform pull request #357
Opened 2021-06-02 10:14 UTC by asadali145

2021-06-02 10:17 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1969/workflows/workflows_id/jobs/1969/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (83.3%): Missing lines 38,60
openedx/adg/lms/courseware_override/helpers.py (25.0%): Missing lines 31-32,34
-------------
Total:   16 lines
Missing: 5 lines
Coverage: 68%
-------------
```

2021-06-02 11:20 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1971/workflows/workflows_id/jobs/1971/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/conftest.py (100%)
openedx/adg/lms/courseware_override/helpers.py (75.0%): Missing lines 32
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
openedx/adg/lms/webinars/tests/test_api_views.py (100%)
-------------
Total:   34 lines
Missing: 1 line
Coverage: 97%
-------------
```

2021-06-02 12:06 UTC, ahmed-faraz46 requested changes

2021-06-02 12:06 UTC, ahmed-faraz46 commented on openedx/adg/lms/applications/managers.py
> +    def get_courses(self, user, is_prereq=False, business_line_courses=False):
@asadali145 here are terminologies we are currently using for different kind of pr reqs
- Program pre reqs (previously known as per reqs)
- Business line pre req (pre reqs of a specific business line)
- Common business line pre req (Pre reqs which are common for all of the business lines)

Let's please update our variable names at all of the places accordingly, in order to enhance the readability.

2021-06-02 12:06 UTC, ahmed-faraz46 commented on openedx/adg/lms/applications/managers.py
> +        courses_list = []
How about writing separate getters for all these three kind of course groups and moving the code below to a utility and utilizing in all three getters?

2021-06-04 07:29 UTC, javeriaejaz-arbisoft approved these changes
LGTM

2021-06-04 10:14 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2001/workflows/workflows_id/jobs/2001/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/views.py (100%)
openedx/adg/lms/conftest.py (100%)
openedx/adg/lms/courseware_override/helpers.py (42.9%): Missing lines 18-19,21,39
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
openedx/adg/lms/webinars/tests/test_api_views.py (100%)
-------------
Total:   71 lines
Missing: 4 lines
Coverage: 94%
-------------
```

2021-06-04 10:58 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2002/workflows/workflows_id/jobs/2002/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/views.py (100%)
openedx/adg/lms/conftest.py (100%)
openedx/adg/lms/courseware_override/helpers.py (42.9%): Missing lines 18-19,21,39
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
openedx/adg/lms/webinars/tests/test_api_views.py (100%)
-------------
Total:   71 lines
Missing: 4 lines
Coverage: 94%
-------------
```

2021-06-04 11:49 UTC, annas-usman approved these changes

2021-06-04 14:35 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2004/workflows/workflows_id/jobs/2004/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/views.py (100%)
openedx/adg/lms/conftest.py (100%)
openedx/adg/lms/courseware_override/helpers.py (42.9%): Missing lines 18-19,21,39
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
openedx/adg/lms/webinars/tests/test_api_views.py (100%)
-------------
Total:   71 lines
Missing: 4 lines
Coverage: 94%
-------------
```

2021-06-04 14:40 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2005/workflows/workflows_id/jobs/2005/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/views.py (100%)
openedx/adg/lms/conftest.py (100%)
openedx/adg/lms/courseware_override/helpers.py (42.9%): Missing lines 18-19,21,39
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
openedx/adg/lms/webinars/tests/test_api_views.py (100%)
-------------
Total:   71 lines
Missing: 4 lines
Coverage: 94%
-------------
```

2021-06-04 14:51 UTC, ahmed-faraz46 approved these changes

2021-06-04 14:52 UTC, merged