LP-2747 - Remove unnecessary queries
OmnipreneurshipAcademy/edx-platform pull request #429
Opened 2021-07-12 17:45 UTC by MunamMubashir-arbisoft

2021-07-13 10:27 UTC, annas-usman approved these changes

2021-07-13 11:00 UTC, javeriaejaz-arbisoft requested changes

2021-07-13 11:00 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/applications/models.py
> +        return '{}'.format(self.course_id)
And f-string here too.

2021-07-13 11:30 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2298/workflows/workflows_id/jobs/2298/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (50.0%): Missing lines 109,422
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/webinars/models.py (0.0%): Missing lines 330
-------------
Total:   6 lines
Missing: 3 lines
Coverage: 50%
-------------
```

2021-07-13 13:00 UTC, javeriaejaz-arbisoft approved these changes

2021-07-13 13:04 UTC, MunamMubashir-arbisoft commented
The tests are all running successfully. The failure is because of the coverage where only a couple line change was made in a commit.

2021-07-13 13:06 UTC, merged

2021-07-14 08:16 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2312/workflows/workflows_id/jobs/2312/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```