LP-2824 Populate course status fields in the ApplicationHub model
OmnipreneurshipAcademy/edx-platform pull request #482
Opened 2021-08-11 09:25 UTC by javeriaejaz-arbisoft

2021-08-11 12:41 UTC, aightmunam requested changes

2021-08-11 12:52 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/applications/management/commands/update_bu_prereq_courses_status.py
> +            ~Q(application_hub__bu_prereq_courses_status=ApplicationHub.COMPLETED)
As per the flow, business line courses are available to user after application submission and program pre-reqs courses. So, to filter out the maximum users, we have placed both checks. Therefore, when user complete bu courses as well, a congratulation email is sent to him/her.

2021-08-11 18:18 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/applications/management/commands/update_program_prereq_courses_status.py
> +                users_with_pre_reqs_completed.append(user)
True but the above is more readable than this:
`users_with_pre_reqs_completed.append(user) if has_user_passed_given_courses(user, courses) else None`
And below isn't recommended style.
`if has_user_passed_given_courses(user, courses): users_with_pre_reqs_completed.append(user)`

2021-08-11 21:47 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2535/workflows/workflows_id/jobs/2535/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/populate_course_status_data.py (68.0%): Missing lines 30-32,51-52,63-64,67
openedx/adg/lms/applications/management/commands/tests/test_populate_course_status_data.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_bu_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_program_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/update_bu_prereq_courses_status.py (90.0%): Missing lines 41-42,45
openedx/adg/lms/applications/management/commands/update_program_prereq_courses_status.py (92.3%): Missing lines 40-41
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/tests/test_views.py (100%)
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   224 lines
Missing: 13 lines
Coverage: 94%
-------------
```

2021-08-11 22:19 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2538/workflows/workflows_id/jobs/2538/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/populate_course_status_data.py (66.7%): Missing lines 25-27,46-47,58-59,62
openedx/adg/lms/applications/management/commands/tests/test_populate_course_status_data.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_bu_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_program_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/update_bu_prereq_courses_status.py (90.0%): Missing lines 40-41,44
openedx/adg/lms/applications/management/commands/update_program_prereq_courses_status.py (92.3%): Missing lines 39-40
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/tests/test_views.py (100%)
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   218 lines
Missing: 13 lines
Coverage: 94%
-------------
```

2021-08-12 07:08 UTC, harris-irfan requested changes

2021-08-12 07:08 UTC, harris-irfan commented on openedx/adg/lms/applications/management/commands/populate_course_status_data.py
> +        users_with_prereqs_enrolled = get_users_with_pre_reqs_enrolled(
`users_enrolled_in_prereqs` would be more appropriate.

2021-08-12 07:08 UTC, harris-irfan commented on openedx/adg/lms/applications/management/commands/populate_course_status_data.py
> +    def set_prereqs_courses_status_to_completed(self, is_bu_prereq=False):
`set_prereq_courses_status_to_completed`

2021-08-12 07:08 UTC, harris-irfan commented
Unit tests are yet to be reviewed.

2021-08-12 11:57 UTC, harris-irfan reviewed
Unit tests review

2021-08-12 12:00 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/applications/management/commands/populate_course_status_data.py
> +            ApplicationHub.objects.filter(is_bu_prerequisite_courses_passed=True).update(
But filter is using two different flags too.

2021-08-12 12:35 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2548/workflows/workflows_id/jobs/2548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/populate_course_status_data.py (66.7%): Missing lines 25-27,46-47,58-59,62
openedx/adg/lms/applications/management/commands/tests/test_populate_course_status_data.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_bu_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_program_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/update_bu_prereq_courses_status.py (90.0%): Missing lines 40-41,44
openedx/adg/lms/applications/management/commands/update_program_prereq_courses_status.py (92.3%): Missing lines 39,42
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/tests/test_views.py (100%)
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   223 lines
Missing: 13 lines
Coverage: 94%
-------------
```

2021-08-12 12:53 UTC, harris-irfan approved these changes
Awesome work done on this ticket!! 👏

2021-08-13 07:24 UTC, aightmunam approved these changes
LGTM! 👏🏼

2021-08-13 07:24 UTC, aightmunam commented on openedx/adg/lms/applications/helpers.py
> +    users_enrolled_in_bu_prereqs = get_users_with_active_enrollments_from_course_groups(
Rename this to `users_enrolled_in_prereqs` as we are considering both bu and program courses

2021-08-13 08:07 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2551/workflows/workflows_id/jobs/2551/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/management/commands/populate_course_status_data.py (66.7%): Missing lines 25-27,46-47,58-59,62
openedx/adg/lms/applications/management/commands/tests/test_populate_course_status_data.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_bu_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_program_prereq_courses_status.py (100%)
openedx/adg/lms/applications/management/commands/update_bu_prereq_courses_status.py (90.0%): Missing lines 40-41,44
openedx/adg/lms/applications/management/commands/update_program_prereq_courses_status.py (92.3%): Missing lines 39,42
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/tests/test_views.py (100%)
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   223 lines
Missing: 13 lines
Coverage: 94%
-------------
```

2021-08-13 08:13 UTC, merged