Test app for post and comments.
OmnipreneurshipAcademy/edx-platform pull request #483
Opened 2021-08-11 13:17 UTC by ahsanarbisoft

For posts list view the URL will be "http://localhost:18000/mysite/" And for admin got Home › Mysite.

2021-08-11 13:20 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2533/workflows/workflows_id/jobs/2533/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/mysite/__init__.py (100%)
openedx/adg/lms/mysite/admin.py (100%)
openedx/adg/lms/mysite/apps.py (100%)
openedx/adg/lms/mysite/constants.py (100%)
openedx/adg/lms/mysite/models.py (90.5%): Missing lines 24,38
openedx/adg/lms/mysite/tests/factories.py (100%)
openedx/adg/lms/mysite/tests/test_models.py (100%)
openedx/adg/lms/mysite/tests/test_views.py (100%)
openedx/adg/lms/mysite/urls.py (100%)
openedx/adg/lms/mysite/views.py (100%)
-------------
Total:   93 lines
Missing: 2 lines
Coverage: 97%
-------------
```

2021-08-12 15:28 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2550/workflows/workflows_id/jobs/2550/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/mysite/__init__.py (100%)
openedx/adg/lms/mysite/admin.py (100%)
openedx/adg/lms/mysite/apps.py (100%)
openedx/adg/lms/mysite/constants.py (100%)
openedx/adg/lms/mysite/models.py (90.0%): Missing lines 31,44
openedx/adg/lms/mysite/tests/factories.py (100%)
openedx/adg/lms/mysite/tests/test_models.py (100%)
openedx/adg/lms/mysite/tests/test_views.py (100%)
openedx/adg/lms/mysite/urls.py (100%)
openedx/adg/lms/mysite/views.py (93.2%): Missing lines 33-34,71
-------------
Total:   130 lines
Missing: 5 lines
Coverage: 96%
-------------
```

2021-08-13 00:48 UTC, javeriaejaz-arbisoft requested changes

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/migrations/0002_auto_20210812_1050.py
> +import openedx.adg.lms.mysite.helpers
There is no helper file in PR. can you please verify that?

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/migrations/0002_auto_20210812_1050.py
> +import openedx.adg.lms.mysite.helpers
Also, we shouldn't be creating 3 migration files. Revert these migrations and create a single migration file.

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/models.py
> +        blank=True
Can we please set image field as required? Also, if we were to add image field as optional, then we should set null=True along with blank=True.

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/models.py
> +    comment = models.CharField(max_length=MAX_COMMENT_TEXT_LENGTH, verbose_name=_('Comment'))
`text` would be a better field name here. Similar model and field name can become confusing in further queries.

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/views.py
> +    def get_context_data(self, **kwargs):
Please add docstring here.

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/views.py
> +        try:
Why do we need try/except here?

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/views.py
> +    fields = ('title', 'description', )
Why have we not added image here?

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/admin.py
> +    list_filter = ['created']
We shouldn't be using list_filter on created field.

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/constants.py
> +MAX_POST_TITLE_LENGTH = 100
Can we increase it at least 150?

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/models.py
> +    title = models.CharField(max_length=MAX_POST_TITLE_LENGTH, unique=True, verbose_name=_('Post title'))
verbose name can only be `Title`.

2021-08-13 00:48 UTC, javeriaejaz-arbisoft commented on openedx/adg/lms/mysite/models.py
> +        verbose_name = _('Posts Comment')
For post model, verbose name `Post` seems more appropriate rather than `Post Comment`

2021-08-16 11:49 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2565/workflows/workflows_id/jobs/2565/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/mysite/__init__.py (100%)
openedx/adg/lms/mysite/admin.py (100%)
openedx/adg/lms/mysite/apps.py (100%)
openedx/adg/lms/mysite/constants.py (100%)
openedx/adg/lms/mysite/models.py (90.0%): Missing lines 32,45
openedx/adg/lms/mysite/tests/factories.py (100%)
openedx/adg/lms/mysite/tests/test_models.py (100%)
openedx/adg/lms/mysite/tests/test_views.py (100%)
openedx/adg/lms/mysite/urls.py (100%)
openedx/adg/lms/mysite/views.py (92.0%): Missing lines 36-37,74,97
-------------
Total:   135 lines
Missing: 6 lines
Coverage: 95%
-------------
```

2021-08-16 11:58 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2566/workflows/workflows_id/jobs/2566/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/mysite/__init__.py (100%)
openedx/adg/lms/mysite/admin.py (100%)
openedx/adg/lms/mysite/apps.py (100%)
openedx/adg/lms/mysite/constants.py (100%)
openedx/adg/lms/mysite/models.py (90.0%): Missing lines 32,45
openedx/adg/lms/mysite/tests/factories.py (100%)
openedx/adg/lms/mysite/tests/test_models.py (100%)
openedx/adg/lms/mysite/tests/test_views.py (100%)
openedx/adg/lms/mysite/urls.py (100%)
openedx/adg/lms/mysite/views.py (92.0%): Missing lines 36-37,74,97
-------------
Total:   135 lines
Missing: 6 lines
Coverage: 95%
-------------
```

2021-08-30 11:26 UTC, asadali145 commented
Closing the PR as we are done with its purpose of learning.

2021-08-30 11:26 UTC, closed without merging