Usman/lp 2459
OmnipreneurshipAcademy/edx-platform pull request #50
Opened 2020-11-29 22:42 UTC by muak50

Unit test for edX OTB emails in student and utils app.
Mandrill package updated from 1.0.57 to 1.0.59

2020-11-29 22:49 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/513/workflows/workflows_id/jobs/513/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/student/tests/test_helpers.py (97.4%): Missing lines 134-135
openedx/adg/lms/utils/tests/test_env_utils.py (100%)
-------------
Total:   87 lines
Missing: 2 lines
Coverage: 97%
-------------
```

2020-11-30 07:52 UTC, zahid-arbisoft requested changes

2020-11-30 07:52 UTC, zahid-arbisoft commented on openedx/adg/lms/student/tests/test_helpers.py
> +    """Test 'compose_and_send_adg_update_email_verification' helper method of student"""
Please use edx recommended docstring style, in all tests

"""
Here
"""

In docstring, for code instead of using ' use `

2020-11-30 07:52 UTC, zahid-arbisoft commented on openedx/adg/lms/student/tests/test_helpers.py
> +# @pytest.mark.usefixtures("user_with_profile")
Please remove commented code

2020-11-30 07:52 UTC, zahid-arbisoft commented on openedx/adg/lms/student/tests/test_helpers.py
> +    """Class contains tests related to course enrollments and course invitation emails"""
Please use edx recommended docstring style, in all tests

"""
Here
"""

2020-11-30 07:52 UTC, zahid-arbisoft commented on openedx/adg/lms/student/tests/test_helpers.py
> +        Test 'compose_and_send_adg_course_enrollment_invitation_email' helper method of
In docstring, for code instead of using ' please use `

2020-11-30 08:30 UTC, annas-usman requested changes

2020-11-30 09:06 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/514/workflows/workflows_id/jobs/514/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/student/tests/test_helpers.py (97.4%): Missing lines 146-147
openedx/adg/lms/utils/tests/test_env_utils.py (100%)
-------------
Total:   87 lines
Missing: 2 lines
Coverage: 97%
-------------
```

2020-11-30 09:13 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/515/workflows/workflows_id/jobs/515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/student/tests/test_helpers.py (97.4%): Missing lines 146-147
openedx/adg/lms/utils/tests/test_env_utils.py (100%)
-------------
Total:   87 lines
Missing: 2 lines
Coverage: 97%
-------------
```

2020-11-30 09:25 UTC, annas-usman approved these changes

2020-11-30 09:26 UTC, zahid-arbisoft approved these changes

2020-11-30 09:37 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/517/workflows/workflows_id/jobs/517/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/student/tests/test_helpers.py (50.0%): Missing lines 23-25,34,36-37,39-40,47-48,63-67,69-70,72,81-82,93,95-96,98-99,107-108,121,123,127-128,137-138,140-141,143-144,146-147
openedx/adg/lms/utils/tests/test_env_utils.py (100%)
-------------
Total:   87 lines
Missing: 39 lines
Coverage: 55%
-------------
```

2020-11-30 10:00 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/518/workflows/workflows_id/jobs/518/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (100%)
openedx/adg/lms/applications/models.py (92.9%): Missing lines 154
openedx/adg/lms/registration_extension/admin.py (100%)
openedx/adg/lms/registration_extension/apps.py (0.0%): Missing lines 4,7-8
openedx/adg/lms/registration_extension/constants.py (100%)
openedx/adg/lms/registration_extension/forms.py (66.7%): Missing lines 35-36,57-58,60,85,87,93,118,129
openedx/adg/lms/registration_extension/models.py (100%)
openedx/adg/lms/student/helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (97.4%): Missing lines 146-147
openedx/adg/lms/user_authn_override/login_form.py (100%)
openedx/adg/lms/user_authn_override/password_reset.py (100%)
openedx/adg/lms/user_authn_override/tests/test_login_form.py (100%)
openedx/adg/lms/user_authn_override/tests/test_password_reset.py (100%)
openedx/adg/lms/utils/env_utils.py (100%)
openedx/adg/lms/utils/tests/test_env_utils.py (100%)
-------------
Total:   257 lines
Missing: 16 lines
Coverage: 93%
-------------
```

2020-11-30 10:25 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/519/workflows/workflows_id/jobs/519/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (100%)
openedx/adg/lms/applications/models.py (92.9%): Missing lines 154
openedx/adg/lms/registration_extension/admin.py (100%)
openedx/adg/lms/registration_extension/apps.py (0.0%): Missing lines 4,7-8
openedx/adg/lms/registration_extension/constants.py (100%)
openedx/adg/lms/registration_extension/forms.py (66.7%): Missing lines 35-36,57-58,60,85,87,93,118,129
openedx/adg/lms/registration_extension/models.py (100%)
openedx/adg/lms/student/helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (97.4%): Missing lines 146-147
openedx/adg/lms/user_authn_override/login_form.py (100%)
openedx/adg/lms/user_authn_override/password_reset.py (100%)
openedx/adg/lms/user_authn_override/tests/test_login_form.py (100%)
openedx/adg/lms/user_authn_override/tests/test_password_reset.py (100%)
openedx/adg/lms/utils/env_utils.py (100%)
openedx/adg/lms/utils/tests/test_env_utils.py (100%)
-------------
Total:   257 lines
Missing: 16 lines
Coverage: 93%
-------------
```

2020-11-30 10:39 UTC, merged

2020-11-30 10:42 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/523/workflows/workflows_id/jobs/523/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/usman/LP-2459-develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```