LP-2837 Message on application hub when application status change
OmnipreneurshipAcademy/edx-platform pull request #502
Opened 2021-08-23 16:22 UTC by ahsanarbisoft

Message on application hub is updated when the application status changes.
**Ticket:** https://philanthropyu.atlassian.net/browse/LP-2837

2021-08-23 16:26 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2635/workflows/workflows_id/jobs/2635/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/views.py (100%)
-------------
Total:   34 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2021-08-24 04:59 UTC, annas-usman approved these changes
LGTM, just few minor suggestions

2021-08-24 04:59 UTC, annas-usman commented on openedx/adg/lms/applications/helpers.py
>      Returns:
Please add space between arguments and Returns statement

2021-08-24 04:59 UTC, annas-usman commented on openedx/adg/lms/applications/helpers.py
>      started or not.
Lets update the docstring to reflect the newly added condition.
```
Decides congratulation messages and instructions based on the requirements completed, whether the courses have been 
started or not and if the admin has waitlisted or accepted the application.
```

2021-08-24 07:33 UTC, asadali145 requested changes
Pls incorporate the changes suggested by Annas as well. Here are a few more suggestion.

2021-08-24 07:33 UTC, asadali145 commented on openedx/adg/lms/applications/helpers.py
> +    is_user_application_exit = UserApplication.objects.filter(user=user).exists()
Pls fix the typo in variable name,

2021-08-24 07:33 UTC, asadali145 commented on openedx/adg/lms/applications/helpers.py
> +    is_user_application_exit = UserApplication.objects.filter(user=user).exists()
Lets use `getattr` to avoid multiple queries.

2021-08-24 07:33 UTC, asadali145 commented on openedx/adg/lms/applications/constants.py
> +    'status.'
Line break can be improved, We should break the first line a bit earlier to enhance readability.

2021-08-24 08:40 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2645/workflows/workflows_id/jobs/2645/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/applications/views.py (100%)
-------------
Total:   33 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2021-08-24 09:27 UTC, asadali145 commented
Pls avoid commit messages like `LP-2837 Code suggestions are incorporated `.

2021-08-24 09:29 UTC, asadali145 commented on openedx/adg/lms/applications/helpers.py
> +    user_application = getattr(user, 'application', False)
It should be `None` instead of `False`.

2021-08-24 09:29 UTC, asadali145 commented on openedx/adg/lms/applications/helpers.py
> +    started or not and if the admin has waitlisted or accepted the application..
Remove extra `.`

2021-08-24 09:31 UTC, asadali145 commented on openedx/adg/lms/applications/views.py
> +        user = self.request.user
Do we really need to change this? We can simply get the user from user_application_hub. And we can do this all in `get_application_hub_instructions `.

2021-08-24 10:08 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2646/workflows/workflows_id/jobs/2646/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
-------------
Total:   31 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2021-08-30 11:25 UTC, asadali145 reviewed
Just a suggestion, Rest looks good to me. Pls rebase your commits and make a single commit only as there are some commits with bad commit messages.

2021-08-30 11:25 UTC, asadali145 commented on openedx/adg/lms/applications/helpers.py
> +        username = user_application.user.username
We are using 2 different relations to access the user, How about getting the user once and save it in a variable and use at both places.

```suggestion
    user = user_application_hub.user
    user_application = getattr(user, 'application', None)
    if user_application:
        username = user.username
```

2021-08-30 12:45 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2648/workflows/workflows_id/jobs/2648/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
-------------
Total:   32 lines
Missing: 0 lines
Coverage: 100%
-------------
```

2021-08-31 06:12 UTC, asadali145 approved these changes

2021-08-31 06:24 UTC, annas-usman approved these changes

2021-08-31 06:30 UTC, merged