LP-2444 Modified User Application & Added Business Lines Model
OmnipreneurshipAcademy/edx-platform pull request #51
Opened 2020-11-30 10:24 UTC by javeriaejaz-arbisoft

2020-11-30 10:49 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/526/workflows/workflows_id/jobs/526/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (0.0%): Missing lines 54
openedx/adg/lms/registration_extension/forms.py (100%)
openedx/adg/lms/registration_extension/models.py (100%)
openedx/adg/lms/user_authn_override/login_form.py (100%)
-------------
Total:   9 lines
Missing: 1 line
Coverage: 88%
-------------
```

2020-11-30 11:27 UTC, zahid-arbisoft requested changes

2020-11-30 11:27 UTC, zahid-arbisoft commented on openedx/adg/lms/applications/migrations/0003_user_application_update_business_line.py
> +                ('logo', models.ImageField(help_text='Accepted extensions: .png, .jpg, .svg', null=True, upload_to='business-lines/logos/', validators=[django.core.validators.FileExtensionValidator((
This migration will not execute since it is already run on dev, do we intend to un-apply all migrations first on dev?

2020-11-30 11:27 UTC, zahid-arbisoft commented on openedx/adg/lms/registration_extension/migrations/0001_initial.py
>                  ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to=settings.AUTH_USER_MODEL)),
Why are we changing previous migrations? I think this migration might have already been run on dev, staging, and prod

2020-11-30 11:27 UTC, zahid-arbisoft commented on openedx/adg/lms/registration_extension/models.py
> +    company = models.ForeignKey(BusinessLine, verbose_name=_('Company'), on_delete=models.CASCADE, null=True)
Do we need migration for these changes?

2020-11-30 11:27 UTC, zahid-arbisoft commented on openedx/adg/lms/registration_extension/migrations/0002_auto_20201126_1256.py
> -            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.BusinessLine'),
Have we removed these fields from `ExtendedUserProfile` model

2020-11-30 12:00 UTC, zahid-arbisoft approved these changes

2020-11-30 12:14 UTC, zahid-arbisoft commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/528/workflows/workflows_id/jobs/528/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/__init__.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/apps.py (100%)
openedx/adg/lms/applications/constants.py (100%)
openedx/adg/lms/applications/handlers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/models.py (95.8%): Missing lines 54
openedx/adg/lms/applications/test/factories.py (100%)
openedx/adg/lms/applications/test/test_handlers.py (100%)
openedx/adg/lms/applications/test/test_helpers.py (100%)
openedx/adg/lms/registration_extension/forms.py (100%)
openedx/adg/lms/registration_extension/models.py (100%)
openedx/adg/lms/user_authn_override/login_form.py (100%)
-------------
Total:   102 lines
Missing: 1 line
Coverage: 99%
-------------
```

2020-11-30 12:49 UTC, ahmed-faraz46 commented
Merging as @zeshanarifios bhai is not available, main commit is already reviewed and the addition commit is reviewed by @zahid-arbisoft.

2020-11-30 12:49 UTC, merged

2020-12-02 06:05 UTC, asadali145 commented on openedx/adg/lms/applications/models.py
> +    business_line = models.OneToOneField(BusinessLine, verbose_name=_('Business Line'),
Why this is **OneToOneField** This must be a **ForiegnKey**, Many applications can have the same business line (Many users can apply for the same business line). @ahmed-faraz46 @zahid-arbisoft @zeshanarifios Right?