LP-2850 technical imporvement in admin dashboard
OmnipreneurshipAcademy/edx-platform pull request #542
Opened 2021-09-08 13:36 UTC by AliAdnanSohail

[LP-2850](https://philanthropyu.atlassian.net/browse/LP-2850)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/###)

***

#### Description:
* Add error message when admin don't have any application in open, waitlist and accepepted state
* Update foreign key related name for education and experience
* Move data to context in webinar description page
* Update permission for inactive account

2021-09-08 13:42 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2784/workflows/workflows_id/jobs/2784/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/tests/test_views.py (100%)
openedx/adg/admin_dashboard/applications/views.py (66.7%): Missing lines 135
openedx/adg/admin_dashboard/views.py (100%)
openedx/adg/lms/applications/api/views.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/webinars/views.py (93.3%): Missing lines 28
-------------
Total:   24 lines
Missing: 2 lines
Coverage: 91%
-------------
```

2021-09-09 11:06 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2789/workflows/workflows_id/jobs/2789/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/tests/test_views.py (100%)
openedx/adg/admin_dashboard/applications/views.py (66.7%): Missing lines 135
openedx/adg/admin_dashboard/views.py (100%)
openedx/adg/lms/applications/api/views.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/webinars/tests/test_views.py (100%)
openedx/adg/lms/webinars/views.py (93.3%): Missing lines 28
-------------
Total:   44 lines
Missing: 2 lines
Coverage: 95%
-------------
```

2021-09-09 11:49 UTC, asadali145 requested changes

2021-09-09 11:49 UTC, asadali145 commented on openedx/adg/admin_dashboard/applications/constants.py
> +        'no_data_error_msg': _('You don\'t have any application to review')
Pls add a fullstop at the end of the sentence also I think `do not` sounds better than `don't`, WDYT?

2021-09-09 11:49 UTC, asadali145 commented on openedx/adg/admin_dashboard/applications/constants.py
> +        'no_data_error_msg': _('You don\'t have any application to review')
Also please add trailing comma as in future if someone adds something else then it will not show up in git diff.

2021-09-09 11:49 UTC, asadali145 commented on openedx/adg/lms/webinars/tests/test_views.py
> +    listing_view_request = RequestFactory().get(reverse('webinar_event', kwargs=kwargs))
Pls update variable name.

2021-09-09 11:49 UTC, asadali145 commented on openedx/adg/lms/webinars/tests/test_views.py
> +    assert 'registration' in context_data
Pls add line-spacing for readability.

2021-09-09 11:49 UTC, asadali145 commented on openedx/adg/lms/webinars/views.py
> +    def get_context_data(self, **kwargs):
Pls add docstring.

2021-09-09 11:49 UTC, asadali145 commented on openedx/adg/lms/webinars/views.py
> +            registration = user.webinar_registrations.filter(webinar__id=self.object.id).first()
Blank line before this would have been appropriate.

2021-09-09 11:59 UTC, aightmunam requested changes

2021-09-09 11:59 UTC, aightmunam commented on openedx/adg/admin_dashboard/views.py
>          """
Let's reflect that user also must be active in the docstring

2021-09-09 11:59 UTC, aightmunam commented on openedx/adg/admin_dashboard/applications/views.py
> +            page_description = APPLICATION_TYPE_INFORMATION.get(self.application_type).get('no_data_error_msg', '')
Let's fetch the type info dict in a variable and use that, like so
```
current_application_type_info = APPLICATION_TYPE_INFORMATION.get(self.application_type)
page_title = current_application_type_info.get('title', '')
page_description = (
	current_application_type_info.get('description', '') if self.total_applications > 0 
	else current_application_type_info.get('no_data_error_msg', '')
)
page_style_class = current_application_type_info.get('style_class', '')

2021-09-09 11:59 UTC, aightmunam commented on openedx/adg/lms/webinars/views.py
> +            registration = user.webinar_registrations.filter(webinar__id=self.object.id).first()
We can use `webinar_id` instead of `webinar__id` and it will save us a join.

2021-09-10 12:40 UTC, omnipreneurshipA commented
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2797/workflows/workflows_id/jobs/2797/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/tests/test_views.py (100%)
openedx/adg/admin_dashboard/applications/views.py (100%)
openedx/adg/admin_dashboard/views.py (100%)
openedx/adg/lms/applications/api/views.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/webinars/tests/test_views.py (100%)
openedx/adg/lms/webinars/views.py (93.3%): Missing lines 40
-------------
Total:   46 lines
Missing: 1 line
Coverage: 97%
-------------
```

2021-09-14 10:20 UTC, aightmunam approved these changes

2021-09-14 10:25 UTC, asadali145 approved these changes

2021-09-14 10:25 UTC, merged